# Generated by Django 5.0.14 on 2025-04-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Users', 'verbose_name_plural': 'User'},
        ),
    ]
