# Generated by Django 5.0.14 on 2025-04-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Breed', 'verbose_name_plural': 'Breeds'},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'Dog', 'verbose_name_plural': 'Dogs'},
        ),
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.CharField(max_length=800, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='Dog Breed'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Dog name'),
        ),
    ]
