# Generated by Django 5.0.14 on 2025-05-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
