# Generated by Django 5.0.14 on 2025-05-24 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.CharField(max_length=800, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='Порода собаки'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя собаки'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='dogparent',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения родителя'),
        ),
        migrations.AlterField(
            model_name='dogparent',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='Родительская порода'),
        ),
        migrations.AlterField(
            model_name='dogparent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя родителя'),
        ),
    ]
